// ============================================================
// COURSE DATA: Graphic Design English Trainer
// 100 bilingual sentences for professor English training
// Organized into 10 stages × 10 sentences each
// ============================================================

export interface Sentence {
  id: number;
  studentEN: string;
  studentKR: string;
  keywords: string[];
  professorEN: string;
  professorKR: string;
}

export interface Stage {
  id: number;
  title: string;
  titleKR: string;
  icon: string;
  colorClass: string;
  description: string;
  descriptionKR: string;
  sentences: Sentence[];
}

export const ALL_SENTENCES: Sentence[] = [
  { id: 1, studentEN: "I think this one feels stronger.", studentKR: "이게 더 강하게 느껴져요.", keywords: ["visual impact", "contrast", "scale", "hierarchy", "gravity"], professorEN: "Let's make \"stronger\" more specific. You are noticing visual impact created by contrast, scale, and hierarchy. For example, the large dark plane works like a visual mass with strong gravity, while the smaller type elements orbit around it, so the viewer's eye understands where to begin.", professorKR: "\"강하다\"는 말을 더 구체화해봅시다. 당신은 대비, 스케일, 위계가 만들어내는 시각적 임팩트를 보고 있습니다. 예를 들어 큰 어두운 면은 강한 시각적 중력을 가진 덩어리처럼 작동하고, 작은 타이포 요소들은 그 주변을 도는 것처럼 배치되어 있어 관람자의 시선이 어디서 시작해야 하는지 알게 됩니다." },
  { id: 2, studentEN: "This one feels cleaner.", studentKR: "이게 더 깔끔해 보여요.", keywords: ["clarity", "negative space", "reduction", "figure-ground"], professorEN: "In design language, that cleanliness comes from clarity, negative space, and reduction. The empty area is not simply blank; it functions as breathing space, allowing the figure-ground relationship to become clearer and the main message to stand apart from visual noise.", professorKR: "디자인 언어로 말하면 그 깔끔함은 명료성, 네거티브 스페이스, 그리고 덜어냄에서 나옵니다. 빈 영역은 단순히 비어 있는 것이 아니라 숨 쉴 공간으로 작동하며, 전경과 배경의 관계를 더 분명하게 만들고 핵심 메시지가 시각적 소음에서 분리되도록 돕습니다." },
  { id: 3, studentEN: "This one looks more professional.", studentKR: "이게 더 전문적으로 보여요.", keywords: ["alignment", "spacing", "typographic control", "grid", "baseline"], professorEN: "You are noticing alignment, spacing, and typographic control, which make the work feel intentional. The grid may be invisible, but the repeated margins and consistent baselines create a sense of order, similar to how gravity stabilizes objects in a visual field.", professorKR: "당신은 정렬, 간격, 타이포그래피 통제를 보고 있습니다. 이런 요소들이 작업을 의도적으로 느끼게 만듭니다. 그리드는 보이지 않을 수 있지만, 반복되는 여백과 일관된 기준선은 시각장 안에서 사물이 중력에 의해 안정되는 것처럼 질서감을 만듭니다." },
  { id: 4, studentEN: "This one feels confusing.", studentKR: "이건 좀 혼란스러워요.", keywords: ["unclear hierarchy", "competing elements", "proximity", "similarity"], professorEN: "That confusion comes from an unclear hierarchy, because several elements are competing for attention at the same time. Gestalt-wise, proximity and similarity are not working together, so the viewer cannot easily group the dots, lines, images, and text into a meaningful structure.", professorKR: "그 혼란은 불명확한 위계에서 나옵니다. 여러 요소가 동시에 주목을 요구하고 있기 때문입니다. 게슈탈트 관점에서 보면 근접성과 유사성이 함께 작동하지 않아, 관람자가 점, 선, 이미지, 텍스트를 의미 있는 구조로 쉽게 묶지 못하고 있습니다." },
  { id: 5, studentEN: "This poster feels too busy.", studentKR: "이 포스터는 너무 복잡해 보여요.", keywords: ["visual density", "information overload", "dominant plane", "visual velocity"], professorEN: "You are noticing visual density. There is too much information at the same level, so the viewer has difficulty finding the main message. The eye has too many possible paths, and because there is no dominant plane or focal point, the visual velocity becomes scattered rather than directed.", professorKR: "당신은 시각적 밀도를 보고 있습니다. 같은 수준의 정보가 너무 많아서 관람자가 핵심 메시지를 찾기 어렵습니다. 시선이 갈 수 있는 길이 너무 많고, 지배적인 면이나 초점이 없기 때문에 시각적 속도감이 한 방향으로 흐르지 못하고 흩어집니다." },
  { id: 6, studentEN: "This one feels more balanced.", studentKR: "이게 더 균형 잡혀 보여요.", keywords: ["visual weight", "compositional stability", "counterbalance", "gravity"], professorEN: "You are responding to visual weight and compositional stability. The balance does not mean both sides are identical; it means the large area, small details, and directional lines compensate for each other, creating a stable gravity across the composition.", professorKR: "당신은 시각적 무게와 구성의 안정성에 반응하고 있습니다. 균형은 양쪽이 똑같다는 뜻이 아닙니다. 큰 영역, 작은 디테일, 방향성을 가진 선들이 서로를 보완하면서 화면 전체에 안정적인 시각적 중력을 만든다는 뜻입니다." },
  { id: 7, studentEN: "This one feels fun.", studentKR: "이건 재미있게 느껴져요.", keywords: ["playful tone", "rhythm", "curved line", "bouncing velocity"], professorEN: "The playful tone comes from rhythm, lively color, and informal visual movement. The repeated dots and curved lines create a bouncing velocity, so the viewer does not read the poster as static information but as an active visual experience.", professorKR: "그 장난스러운 톤은 리듬, 생동감 있는 색, 비격식적인 시각적 움직임에서 나옵니다. 반복되는 점과 곡선은 튀어 오르는 듯한 시각적 속도감을 만들기 때문에, 관람자는 이 포스터를 정적인 정보가 아니라 활동적인 시각 경험으로 읽게 됩니다." },
  { id: 8, studentEN: "This one looks more serious.", studentKR: "이건 더 진지해 보여요.", keywords: ["restrained palette", "stable structure", "vertical alignment", "rectangular plane"], professorEN: "The seriousness comes from a restrained palette and a stable structure that reduces visual playfulness. The vertical alignment, limited color range, and heavy rectangular planes create visual gravity, making the work feel controlled and less casual.", professorKR: "진지함은 절제된 팔레트와 안정적인 구조에서 나옵니다. 이는 시각적 장난기를 줄입니다. 수직 정렬, 제한된 색 범위, 무거운 사각형 면은 시각적 중력을 만들어 작업을 통제되고 덜 캐주얼하게 느끼게 합니다." },
  { id: 9, studentEN: "This one feels more modern.", studentKR: "이게 더 현대적으로 느껴져요.", keywords: ["minimal composition", "grid order", "typographic restraint", "margin"], professorEN: "In design language, that modern feeling comes from minimal composition, grid-based order, and typographic restraint. The design reduces ornamental noise and uses plane, margin, and alignment as the main language, which gives the viewer a precise and contemporary reading path.", professorKR: "디자인 언어로 말하면 그 현대적인 느낌은 미니멀한 구성, 그리드 기반 질서, 절제된 타이포그래피에서 나옵니다. 이 디자인은 장식적 소음을 줄이고 면, 여백, 정렬을 주요 언어로 사용하여 관람자에게 정밀하고 동시대적인 읽기 경로를 제공합니다." },
  { id: 10, studentEN: "This one looks old-fashioned.", studentKR: "이건 좀 오래된 스타일 같아요.", keywords: ["traditional tone", "ornamental structure", "symmetry", "low velocity"], professorEN: "You are noticing a traditional visual tone, probably created by ornamental structure, color choice, or type style. The decorative lines and symmetrical composition may create stability, but they also reduce visual velocity, making the work feel closer to an older editorial or poster convention.", professorKR: "당신은 전통적인 시각 톤을 보고 있습니다. 아마 장식적 구조, 색 선택, 서체 스타일에서 만들어졌을 것입니다. 장식적 선과 대칭적 구성은 안정감을 만들 수 있지만, 동시에 시각적 속도감을 줄여 이 작업을 오래된 편집 디자인이나 포스터 관습에 가깝게 느끼게 합니다." },
  { id: 11, studentEN: "The layout feels empty.", studentKR: "레이아웃이 비어 보여요.", keywords: ["negative space", "unresolved space", "compositional anchor"], professorEN: "Empty space can be useful, but here the negative space feels unresolved because it does not yet support a clear focal point. If the blank plane had stronger gravity or a clearer relationship to the title, it could become intentional silence rather than unused space.", professorKR: "빈 공간은 유용할 수 있지만, 여기서는 네거티브 스페이스가 아직 해결되지 않은 것처럼 느껴집니다. 명확한 초점을 지지하지 못하기 때문입니다. 빈 면이 더 강한 시각적 중력을 갖거나 제목과 더 분명한 관계를 맺는다면, 사용되지 않은 공간이 아니라 의도된 침묵이 될 수 있습니다." },
  { id: 12, studentEN: "This one feels more memorable.", studentKR: "이게 더 기억에 남아요.", keywords: ["visual hook", "silhouette", "contrast", "point of gravity"], professorEN: "That memorability comes from a clear visual hook, strong silhouette, and contrast that stays in the viewer's mind. A memorable design often has one dominant shape or gesture, almost like a single point of gravity that the whole composition can be recalled through.", professorKR: "그 기억성은 명확한 시각적 후크, 강한 실루엣, 관람자의 마음에 남는 대비에서 나옵니다. 기억에 남는 디자인은 종종 하나의 지배적인 형태나 제스처를 갖고 있으며, 전체 구성을 떠올리게 하는 하나의 중력점처럼 작동합니다." },
  { id: 13, studentEN: "This one feels random.", studentKR: "이건 좀 무작위처럼 느껴져요.", keywords: ["visual rule", "hidden system", "rhythm", "proximity", "directional flow"], professorEN: "Randomness can be expressive, but here the visual rule is not clear enough, so the placement feels accidental. Even experimental composition needs a hidden system, such as repeated angle, rhythm, proximity, or directional flow, so the viewer can sense intention behind disorder.", professorKR: "무작위성은 표현적일 수 있지만, 여기서는 시각적 규칙이 충분히 분명하지 않아 배치가 우연처럼 느껴집니다. 실험적인 구성도 반복되는 각도, 리듬, 근접성, 방향 흐름 같은 숨은 시스템이 필요합니다. 그래야 관람자가 무질서 뒤의 의도를 감지할 수 있습니다." },
  { id: 14, studentEN: "This one feels dynamic.", studentKR: "이건 역동적으로 느껴져요.", keywords: ["movement", "rhythm", "diagonal energy", "visual velocity"], professorEN: "You are noticing movement and rhythm, especially the diagonal energy that makes the composition feel active. Diagonal lines increase visual velocity because they resist static gravity, so the viewer's eye moves through the poster rather than staying fixed in one place.", professorKR: "당신은 움직임과 리듬을 보고 있습니다. 특히 구성을 활동적으로 느끼게 하는 대각선 에너지를 보고 있습니다. 대각선은 정적인 중력에 저항하기 때문에 시각적 속도감을 높입니다. 그래서 관람자의 시선은 한 곳에 고정되지 않고 포스터 안을 이동하게 됩니다." },
  { id: 15, studentEN: "This one feels too static.", studentKR: "이건 너무 정적으로 느껴져요.", keywords: ["predictable structure", "low movement", "scale contrast", "rhythm"], professorEN: "The composition feels static because the structure is predictable and does not create enough visual movement. The vertical and horizontal planes are stable, but without contrast in scale, direction, or rhythm, the viewer's eye has little reason to travel.", professorKR: "이 구성은 구조가 예측 가능하고 충분한 시각적 움직임을 만들지 않기 때문에 정적으로 느껴집니다. 수직·수평 면은 안정적이지만, 스케일, 방향, 리듬의 대비가 없으면 관람자의 시선이 이동할 이유가 적어집니다." },
  { id: 16, studentEN: "This one feels safe.", studentKR: "이건 안전하게 느껴져요.", keywords: ["low visual risk", "distinctive decision", "tension", "interruption"], professorEN: "\"Safe\" means the layout is controlled, but it may need more visual risk or a stronger distinctive decision. The grid is doing its job, but the forms are not yet creating tension, interruption, or velocity, so the design feels correct but not memorable.", professorKR: "\"안전하다\"는 말은 레이아웃이 통제되어 있다는 뜻입니다. 하지만 더 큰 시각적 리스크나 더 뚜렷한 결정이 필요할 수 있습니다. 그리드는 제 역할을 하고 있지만, 형태들이 아직 긴장, 중단, 속도감을 만들지 못해 디자인이 맞기는 하지만 기억에 남지는 않습니다." },
  { id: 17, studentEN: "This one feels experimental.", studentKR: "이건 실험적으로 느껴져요.", keywords: ["visual risk", "internal rule", "scattered shape", "angle logic"], professorEN: "Experimental design means the work takes visual risk, but it still needs an internal rule to guide the viewer. If the scattered shapes share a rhythm, angle, or proximity logic, the composition can feel experimental without becoming random.", professorKR: "실험적 디자인은 작업이 시각적 리스크를 감수한다는 뜻입니다. 그러나 관람자를 안내할 내부 규칙은 여전히 필요합니다. 흩어진 형태들이 리듬, 각도, 근접성의 논리를 공유한다면, 구성은 무작위가 되지 않고도 실험적으로 느껴질 수 있습니다." },
  { id: 18, studentEN: "This one feels emotional.", studentKR: "이건 감정적으로 느껴져요.", keywords: ["atmosphere", "visual tone", "soft edge", "slow rhythm"], professorEN: "That emotion comes from atmosphere, visual tone, and the way color and composition shape the viewer's mood. The blurred boundary between figure and ground, the soft edges, and the slower visual rhythm create a more intimate emotional field.", professorKR: "그 감정은 분위기, 시각 톤, 그리고 색과 구성이 관람자의 기분을 형성하는 방식에서 나옵니다. 전경과 배경 사이의 흐릿한 경계, 부드러운 가장자리, 느린 시각 리듬이 더 친밀한 감정의 장을 만듭니다." },
  { id: 19, studentEN: "This one is easier to read.", studentKR: "이건 읽기 더 쉬워요.", keywords: ["legibility", "type size", "spacing", "figure-ground separation"], professorEN: "You are noticing legibility. The contrast, type size, and spacing help the viewer read the message more easily. The type has enough separation from the background plane, so the figure-ground relationship supports reading rather than interrupting it.", professorKR: "당신은 가독성을 보고 있습니다. 대비, 글자 크기, 간격이 관람자가 메시지를 더 쉽게 읽도록 돕습니다. 글자는 배경 면과 충분히 분리되어 있어, 전경-배경 관계가 읽기를 방해하지 않고 오히려 지지합니다." },
  { id: 20, studentEN: "The message feels unclear.", studentKR: "메시지가 불명확하게 느껴져요.", keywords: ["communication goal", "concept-form alignment", "Gestalt"], professorEN: "That means the concept and form are not fully aligned, so the communication goal is still weak. The visual elements may be interesting individually, but they do not yet form one clear Gestalt, so the viewer cannot synthesize them into a single message.", professorKR: "그것은 개념과 형식이 완전히 정렬되어 있지 않아 커뮤니케이션 목표가 아직 약하다는 뜻입니다. 시각 요소들은 개별적으로 흥미로울 수 있지만, 아직 하나의 명확한 게슈탈트를 이루지 못해 관람자가 그것들을 하나의 메시지로 종합하기 어렵습니다." },
  { id: 21, studentEN: "This one catches my eye first.", studentKR: "이게 먼저 눈에 들어와요.", keywords: ["entry point", "focal point", "scale", "position", "gravity"], professorEN: "You are identifying the entry point. The focal point attracts the viewer before the rest of the information is read. This usually happens when scale, contrast, and position combine to create a strong point of gravity in the visual field.", professorKR: "당신은 진입점을 찾아내고 있습니다. 초점은 나머지 정보가 읽히기 전에 관람자의 시선을 끌어옵니다. 이는 보통 스케일, 대비, 위치가 결합하여 시각장 안에 강한 중력점을 만들 때 발생합니다." },
  { id: 22, studentEN: "This one feels boring.", studentKR: "이건 지루하게 느껴져요.", keywords: ["low contrast", "weak tension", "predictable rhythm", "visual velocity"], professorEN: "Let's translate that carefully. The work may feel boring because it has low contrast, weak tension, and predictable rhythm. If all elements have similar size, spacing, and direction, the viewer experiences no change in visual velocity.", professorKR: "그 말을 조심스럽게 번역해봅시다. 이 작업은 낮은 대비, 약한 긴장, 예측 가능한 리듬 때문에 지루하게 느껴질 수 있습니다. 모든 요소가 비슷한 크기, 간격, 방향을 가지면 관람자는 시각적 속도감의 변화를 경험하지 못합니다." },
  { id: 23, studentEN: "This one looks stylish.", studentKR: "이건 스타일리시해 보여요.", keywords: ["visual tone", "formal consistency", "type", "color", "proportion"], professorEN: "That stylish feeling comes from a controlled visual tone and formal consistency across the elements. The style is not just decoration; it is a consistent system of type, color, proportion, and spacing that gives the work a recognizable attitude.", professorKR: "그 스타일리시한 느낌은 통제된 시각 톤과 요소들 사이의 형식적 일관성에서 나옵니다. 스타일은 단순한 장식이 아닙니다. 서체, 색, 비례, 간격의 일관된 시스템이며, 작업에 인식 가능한 태도를 부여합니다." },
  { id: 24, studentEN: "Something feels awkward here.", studentKR: "여기 뭔가 어색해요.", keywords: ["proportion", "alignment", "unstable relationship", "visual gravity"], professorEN: "You are noticing unresolved proportion or weak alignment, which makes the relationship between elements feel unstable. The visual gravity is slightly off; one object seems to float without enough connection to the grid, margin, or surrounding plane.", professorKR: "당신은 해결되지 않은 비례나 약한 정렬을 보고 있습니다. 이것이 요소들 사이의 관계를 불안정하게 느끼게 합니다. 시각적 중력이 살짝 어긋나 있어, 한 요소가 그리드, 여백, 주변 면과 충분히 연결되지 못한 채 떠 있는 것처럼 보입니다." },
  { id: 25, studentEN: "This one looks cool.", studentKR: "이건 멋져 보여요.", keywords: ["contemporary attitude", "strong form language", "crop", "restraint"], professorEN: "\"Cool\" here can be translated as a contemporary visual attitude supported by strong form language. The sharp contrast, cropped image, and confident negative space create distance and control, which makes the work feel less sentimental and more current.", professorKR: "여기서 \"멋지다\"는 말은 강한 조형 언어가 뒷받침하는 동시대적 시각 태도로 번역할 수 있습니다. 날카로운 대비, 크롭된 이미지, 자신감 있는 네거티브 스페이스가 거리감과 통제감을 만들어 작업을 덜 감상적이고 더 현재적으로 느끼게 합니다." },
  { id: 26, studentEN: "This one feels cute.", studentKR: "이건 귀엽게 느껴져요.", keywords: ["friendly proportion", "rounded form", "soft contrast"], professorEN: "The cute tone comes from softer forms, friendly proportions, and a less aggressive visual rhythm. Rounded shapes, smaller scale, and warm spacing reduce visual pressure, so the viewer experiences the design as approachable rather than forceful.", professorKR: "귀여운 톤은 부드러운 형태, 친근한 비례, 덜 공격적인 시각 리듬에서 나옵니다. 둥근 형태, 작은 스케일, 따뜻한 간격은 시각적 압박을 줄여 관람자가 디자인을 강압적이기보다 다가가기 쉬운 것으로 경험하게 합니다." },
  { id: 27, studentEN: "This one feels heavy.", studentKR: "이건 무겁게 느껴져요.", keywords: ["visual weight", "dark value", "dense composition", "thick typography"], professorEN: "The heaviness comes from strong visual weight, darker values, and a dense composition. Large black planes or thick typography create gravity, pulling the viewer's attention downward or inward and making the image feel physically weighty.", professorKR: "무거움은 강한 시각적 무게, 어두운 명도, 밀도 높은 구성에서 나옵니다. 큰 검은 면이나 두꺼운 타이포그래피는 중력을 만들어 관람자의 주의를 아래쪽이나 안쪽으로 끌어당기고, 이미지를 물리적으로 무게감 있게 느끼게 합니다." },
  { id: 28, studentEN: "This one feels light.", studentKR: "이건 가볍게 느껴져요.", keywords: ["visual openness", "low density", "soft contrast", "low gravity"], professorEN: "You are noticing visual openness, low density, and soft contrast, which reduce visual pressure. Thin lines, pale values, and generous negative space create a low-gravity composition, so the elements feel like they are floating rather than pressing down.", professorKR: "당신은 시각적 개방감, 낮은 밀도, 부드러운 대비를 보고 있습니다. 이것들이 시각적 압박을 줄입니다. 얇은 선, 옅은 명도, 넉넉한 네거티브 스페이스는 낮은 중력의 구성을 만들어 요소들이 눌러앉기보다 떠 있는 것처럼 느껴지게 합니다." },
  { id: 29, studentEN: "This design feels loud.", studentKR: "이 디자인은 시끄럽게 느껴져요.", keywords: ["high saturation", "strong contrast", "assertive typography", "visual volume"], professorEN: "That loudness comes from high saturation, strong contrast, and assertive typography. When many colors and shapes compete with similar intensity, the composition increases visual volume, almost as if every element is speaking at once.", professorKR: "그 시끄러움은 높은 채도, 강한 대비, 주장적인 타이포그래피에서 나옵니다. 많은 색과 형태가 비슷한 강도로 경쟁하면, 구성은 시각적 볼륨을 높이고 마치 모든 요소가 동시에 말하는 것처럼 느껴집니다." },
  { id: 30, studentEN: "This one feels quiet.", studentKR: "이건 조용하게 느껴져요.", keywords: ["low contrast", "restrained color", "subtle hierarchy", "slow velocity"], professorEN: "The quiet tone comes from low contrast, restrained color, and a subtle hierarchy. The forms do not push aggressively toward the viewer; instead, they create a slower visual velocity that invites careful looking.", professorKR: "조용한 톤은 낮은 대비, 절제된 색, 미묘한 위계에서 나옵니다. 형태들은 관람자를 향해 공격적으로 밀고 나오지 않고, 대신 천천히 바라보도록 초대하는 느린 시각적 속도감을 만듭니다." },
  { id: 31, studentEN: "This one feels elegant.", studentKR: "이건 우아하게 느껴져요.", keywords: ["refined proportion", "restrained detail", "graceful spacing"], professorEN: "Elegance here comes from refined proportion, restrained detail, and graceful spacing. The relationship between line, plane, and margin feels measured, so the composition does not need excessive decoration to feel complete.", professorKR: "여기서 우아함은 정제된 비례, 절제된 디테일, 품위 있는 간격에서 나옵니다. 선, 면, 여백 사이의 관계가 잘 측정된 것처럼 느껴지기 때문에, 구성은 과도한 장식 없이도 완성되어 보입니다." },
  { id: 32, studentEN: "This one looks messy.", studentKR: "이건 지저분해 보여요.", keywords: ["weak organization", "inconsistent spacing", "visual clutter", "proximity"], professorEN: "You are noticing weak organization, inconsistent spacing, and visual clutter. The viewer cannot easily group the elements through proximity or similarity, so the composition breaks into unrelated parts instead of one coherent system.", professorKR: "당신은 약한 조직화, 불일치한 간격, 시각적 혼잡을 보고 있습니다. 관람자는 근접성이나 유사성을 통해 요소들을 쉽게 묶지 못하기 때문에, 구성은 하나의 일관된 시스템이 아니라 서로 관련 없는 부분들로 쪼개집니다." },
  { id: 33, studentEN: "This one is simple.", studentKR: "이건 단순해요.", keywords: ["reduction", "essential form", "point", "line", "plane"], professorEN: "That simplicity comes from reduction and the use of essential forms rather than unnecessary decoration. When a design uses only a few points, lines, or planes, every decision becomes more visible and must carry more meaning.", professorKR: "그 단순함은 덜어냄과 불필요한 장식 대신 본질적인 형태를 사용하는 데서 나옵니다. 디자인이 몇 개의 점, 선, 면만 사용할 때, 모든 결정은 더 잘 보이고 더 많은 의미를 감당해야 합니다." },
  { id: 34, studentEN: "This one feels too simple.", studentKR: "이건 너무 단순하게 느껴져요.", keywords: ["insufficient tension", "weak focal point", "figure-ground relationship"], professorEN: "Simplicity becomes a problem when there is not enough tension, focal point, or developed visual idea. A minimal design still needs contrast, rhythm, or a strong figure-ground relationship; otherwise, reduction becomes emptiness.", professorKR: "단순함은 충분한 긴장, 초점, 발전된 시각 아이디어가 없을 때 문제가 됩니다. 미니멀한 디자인도 대비, 리듬, 강한 전경-배경 관계가 필요합니다. 그렇지 않으면 덜어냄은 비어 있음이 됩니다." },
  { id: 35, studentEN: "This one feels complicated.", studentKR: "이건 복잡하게 느껴져요.", keywords: ["excessive layers", "information structure", "grouping", "sequence"], professorEN: "The complexity comes from too many layers and an information structure that asks the viewer to process too much at once. Complexity can work if there is grouping, sequence, and hierarchy, but here the eye does not yet know how to travel through the layers.", professorKR: "복잡함은 너무 많은 레이어와 관람자에게 한 번에 너무 많은 것을 처리하도록 요구하는 정보 구조에서 나옵니다. 복잡성은 그룹화, 순서, 위계가 있으면 작동할 수 있지만, 여기서는 시선이 그 레이어들을 어떻게 지나가야 하는지 아직 알기 어렵습니다." },
  { id: 36, studentEN: "This one feels direct.", studentKR: "이건 직접적으로 느껴져요.", keywords: ["clear message", "strong hierarchy", "immediate readability", "dominant element"], professorEN: "Directness comes from a clear message, strong hierarchy, and immediate readability. The dominant text or image acts as the first point of contact, and the remaining elements support that point instead of competing with it.", professorKR: "직접성은 명확한 메시지, 강한 위계, 즉각적인 가독성에서 나옵니다. 지배적인 텍스트나 이미지는 첫 접점으로 작동하고, 나머지 요소들은 그것과 경쟁하지 않고 그 지점을 지지합니다." },
  { id: 37, studentEN: "This one feels vague.", studentKR: "이건 모호하게 느껴져요.", keywords: ["ambiguous concept", "unclear visual direction", "attitude mismatch"], professorEN: "That vagueness means the concept is still ambiguous and the visual direction is not yet fully defined. The image, type, and composition do not point toward the same attitude, so the viewer receives atmosphere but not a clear design intention.", professorKR: "그 모호함은 개념이 아직 애매하고 시각 방향이 충분히 정의되지 않았다는 뜻입니다. 이미지, 서체, 구성이 같은 태도를 향하지 않기 때문에 관람자는 분위기는 받지만 명확한 디자인 의도는 받지 못합니다." },
  { id: 38, studentEN: "This one feels soft.", studentKR: "이건 부드럽게 느껴져요.", keywords: ["low contrast", "gentle color", "curved line", "blurred edge"], professorEN: "Softness comes from lower contrast, gentle color, and rounded visual rhythm. Curved lines and blurred edges reduce sharp figure-ground separation, making the visual field feel more fluid and less forceful.", professorKR: "부드러움은 낮은 대비, 온화한 색, 둥근 시각 리듬에서 나옵니다. 곡선과 흐릿한 가장자리는 날카로운 전경-배경 분리를 줄여, 시각장을 더 유동적이고 덜 강압적으로 느끼게 합니다." },
  { id: 39, studentEN: "This one feels sharp.", studentKR: "이건 날카롭게 느껴져요.", keywords: ["angular form", "strong edge", "high contrast", "aggressive voice"], professorEN: "The sharp feeling comes from angular forms, strong edges, and high contrast. The lines cut through the plane with higher velocity, creating a more decisive and sometimes more aggressive visual voice.", professorKR: "날카로운 느낌은 각진 형태, 강한 가장자리, 높은 대비에서 나옵니다. 선들이 더 높은 속도감으로 면을 가르며 지나가고, 더 단호하고 때로는 공격적인 시각 목소리를 만듭니다." },
  { id: 40, studentEN: "This one has a strong mood.", studentKR: "이건 분위기가 강해요.", keywords: ["coherent atmosphere", "consistent visual tone", "emotional field"], professorEN: "The strong mood comes from coherent atmosphere and consistent visual tone across the whole composition. Color, texture, type, and spacing are working together as one Gestalt, so the viewer reads the work as a unified emotional field.", professorKR: "강한 분위기는 전체 구성에 걸친 일관된 분위기와 시각 톤에서 나옵니다. 색, 질감, 서체, 간격이 하나의 게슈탈트로 함께 작동하기 때문에, 관람자는 이 작업을 통합된 감정의 장으로 읽습니다." },
  { id: 41, studentEN: "The mood feels weak.", studentKR: "분위기가 약하게 느껴져요.", keywords: ["inconsistent tone", "insufficient atmosphere", "emotional reading"], professorEN: "The mood feels weak because the tone is inconsistent and the atmosphere is not supported by enough visual decisions. Some elements suggest softness while others suggest intensity, so the viewer cannot settle into one clear emotional reading.", professorKR: "분위기가 약한 이유는 톤이 일관되지 않고, 충분한 시각적 결정이 분위기를 지지하지 못하기 때문입니다. 어떤 요소는 부드러움을 말하고 다른 요소는 강도를 말하기 때문에, 관람자는 하나의 명확한 감정적 읽기에 머물지 못합니다." },
  { id: 42, studentEN: "This one feels impressive.", studentKR: "이건 인상적이에요.", keywords: ["visual hook", "distinct composition", "scale shift", "visual event"], professorEN: "That impression comes from a strong visual hook, distinct composition, and a memorable form. The scale shift between the main object and the surrounding elements creates tension, making the viewer feel that something significant is happening.", professorKR: "그 인상은 강한 시각적 후크, 뚜렷한 구성, 기억에 남는 형태에서 나옵니다. 주요 대상과 주변 요소 사이의 스케일 변화가 긴장을 만들고, 관람자는 무언가 중요한 일이 일어나고 있다고 느낍니다." },
  { id: 43, studentEN: "This one feels flat.", studentKR: "이건 평평하게 느껴져요.", keywords: ["low depth", "weak contrast", "spatial tension", "overlap"], professorEN: "The flatness comes from low depth, weak contrast, and limited spatial tension. If the planes had more overlap, shadow, scale variation, or foreground-background separation, the composition would gain stronger spatial hierarchy.", professorKR: "평평함은 낮은 깊이감, 약한 대비, 제한된 공간적 긴장에서 나옵니다. 면들이 더 많이 겹치거나, 그림자, 스케일 변화, 전경-배경 분리가 있었다면 구성은 더 강한 공간 위계를 얻게 되었을 것입니다." },
  { id: 44, studentEN: "This one feels dimensional.", studentKR: "이건 입체적으로 느껴져요.", keywords: ["depth", "layering", "spatial hierarchy", "foreground-middle-background"], professorEN: "You are noticing depth, layering, and spatial hierarchy, which make the design feel more dimensional. Overlapping planes and scale differences create a sense of foreground, middle ground, and background, so the viewer's eye moves through space.", professorKR: "당신은 깊이감, 레이어링, 공간 위계를 보고 있습니다. 이것이 디자인을 더 입체적으로 느끼게 합니다. 겹치는 면과 스케일 차이는 전경, 중경, 배경의 감각을 만들고, 관람자의 시선이 공간을 통과하게 합니다." },
  { id: 45, studentEN: "There is too much text.", studentKR: "텍스트가 너무 많아요.", keywords: ["information hierarchy", "text grouping", "scanning structure"], professorEN: "This is an information hierarchy issue. Too much text weakens the viewer's ability to find the main message. If the text is grouped by proximity and divided by scale, weight, or spacing, the information can become easier to scan.", professorKR: "이것은 정보 위계의 문제입니다. 텍스트가 너무 많으면 관람자가 핵심 메시지를 찾는 능력이 약해집니다. 텍스트를 근접성에 따라 묶고, 스케일, 굵기, 간격으로 나누면 정보는 더 쉽게 훑어볼 수 있게 됩니다." },
  { id: 46, studentEN: "There is not enough text.", studentKR: "텍스트가 충분하지 않아요.", keywords: ["context", "typographic anchor", "explanatory layer"], professorEN: "That means the visual may need more context or verbal support to make the message complete. Sometimes a typographic anchor or a short explanatory layer can help the viewer understand the image without reducing the visual impact.", professorKR: "그것은 시각 요소가 메시지를 완성하기 위해 더 많은 맥락이나 언어적 지지가 필요하다는 뜻입니다. 때로는 타이포그래픽 앵커나 짧은 설명 레이어가 시각적 임팩트를 줄이지 않고도 관람자가 이미지를 이해하도록 도울 수 있습니다." },
  { id: 47, studentEN: "The font choice feels wrong.", studentKR: "폰트 선택이 잘못된 것 같아요.", keywords: ["typographic voice", "tone mismatch", "font personality", "concept alignment"], professorEN: "You are noticing a typographic voice mismatch. The font carries its own visual personality, and if that personality does not match the concept, the design sends conflicting signals. The form of the letter itself is part of the message.", professorKR: "당신은 타이포그래픽 목소리의 불일치를 보고 있습니다. 폰트는 자체적인 시각적 개성을 가지고 있으며, 그 개성이 개념과 맞지 않으면 디자인은 상충하는 신호를 보냅니다. 글자의 형태 자체가 메시지의 일부입니다." },
  { id: 48, studentEN: "The colors feel off.", studentKR: "색이 좀 어색해요.", keywords: ["color harmony", "value relationship", "saturation balance", "visual temperature"], professorEN: "You are noticing a color harmony problem. The colors may not share a consistent value relationship or saturation level, so they create tension without intention. Color decisions should support the visual temperature and mood of the concept, not contradict it.", professorKR: "당신은 색채 조화의 문제를 보고 있습니다. 색들이 일관된 명도 관계나 채도 수준을 공유하지 않아, 의도 없이 긴장을 만들고 있습니다. 색 결정은 개념의 시각적 온도와 분위기를 지지해야 하며, 그것에 반해서는 안 됩니다." },
  { id: 49, studentEN: "The image and text feel disconnected.", studentKR: "이미지와 텍스트가 따로 노는 것 같아요.", keywords: ["image-text relationship", "visual unity", "proximity", "shared axis"], professorEN: "The image and text need to share a visual logic, such as a common axis, proximity, or color relationship. If they are placed without a shared rule, they will feel like two separate objects rather than one integrated composition.", professorKR: "이미지와 텍스트는 공통 축, 근접성, 색 관계 같은 시각적 논리를 공유해야 합니다. 공유된 규칙 없이 배치되면, 하나의 통합된 구성이 아니라 두 개의 별개 사물처럼 느껴집니다." },
  { id: 50, studentEN: "This one feels more intentional.", studentKR: "이게 더 의도적으로 느껴져요.", keywords: ["design decision", "visual system", "consistency", "purposeful form"], professorEN: "Intentionality means every visual decision has a reason. The spacing, scale, and color are not accidental; they follow a consistent visual system. When the viewer senses that each choice was made with purpose, the work feels resolved and authoritative.", professorKR: "의도성은 모든 시각적 결정에 이유가 있다는 뜻입니다. 간격, 스케일, 색은 우연이 아니라 일관된 시각 시스템을 따릅니다. 관람자가 각 선택이 목적을 가지고 이루어졌다고 느낄 때, 작업은 해결되고 권위 있게 느껴집니다." },
  { id: 51, studentEN: "This one feels more focused.", studentKR: "이게 더 집중된 느낌이에요.", keywords: ["focal clarity", "visual hierarchy", "dominant element", "reading path"], professorEN: "That focus comes from a clear focal point and a strong visual hierarchy. One element dominates, and the rest support it, so the viewer's reading path is clear and efficient.", professorKR: "그 집중감은 명확한 초점과 강한 시각 위계에서 나옵니다. 하나의 요소가 지배하고 나머지가 그것을 지지하기 때문에, 관람자의 읽기 경로가 명확하고 효율적입니다." },
  { id: 52, studentEN: "This one feels scattered.", studentKR: "이건 흩어진 느낌이에요.", keywords: ["no focal point", "equal weight", "visual noise", "competing elements"], professorEN: "The scattered feeling comes from elements that all carry equal visual weight, so there is no clear focal point. The eye does not know where to begin, and the composition feels like visual noise rather than a directed message.", professorKR: "흩어진 느낌은 모든 요소가 동등한 시각적 무게를 가져 명확한 초점이 없는 데서 나옵니다. 시선이 어디서 시작해야 할지 모르고, 구성은 방향성 있는 메시지가 아니라 시각적 소음처럼 느껴집니다." },
  { id: 53, studentEN: "This one feels more resolved.", studentKR: "이게 더 완성된 느낌이에요.", keywords: ["visual resolution", "system coherence", "no loose ends", "intentional decisions"], professorEN: "A resolved design means every element has found its place within the visual system. There are no loose ends; the spacing, scale, and color decisions all reinforce each other, creating a sense of completeness.", professorKR: "완성된 디자인은 모든 요소가 시각 시스템 안에서 자신의 자리를 찾았다는 뜻입니다. 느슨한 끝이 없고, 간격, 스케일, 색 결정이 서로를 강화하여 완결성의 감각을 만듭니다." },
  { id: 54, studentEN: "This one feels unfinished.", studentKR: "이건 미완성처럼 느껴져요.", keywords: ["unresolved tension", "incomplete system", "visual gap", "missing anchor"], professorEN: "The unfinished feeling comes from unresolved tension or an incomplete visual system. There may be a missing anchor, an inconsistent spacing decision, or a color that does not yet belong to the overall palette.", professorKR: "미완성된 느낌은 해결되지 않은 긴장이나 불완전한 시각 시스템에서 나옵니다. 앵커가 빠져 있거나, 간격 결정이 일관되지 않거나, 전체 팔레트에 아직 속하지 않는 색이 있을 수 있습니다." },
  { id: 55, studentEN: "This one feels more original.", studentKR: "이게 더 독창적으로 느껴져요.", keywords: ["distinctive decision", "unexpected form", "visual surprise", "authorial voice"], professorEN: "Originality in design comes from a distinctive decision that the viewer did not expect. It could be an unexpected form, a surprising color relationship, or an authorial voice in the typography that makes the work feel like it could only have been made by this designer.", professorKR: "디자인에서 독창성은 관람자가 예상하지 못한 뚜렷한 결정에서 나옵니다. 예상치 못한 형태, 놀라운 색 관계, 또는 이 디자이너만이 만들 수 있었다는 느낌을 주는 타이포그래피의 작가적 목소리일 수 있습니다." },
  { id: 56, studentEN: "This one feels generic.", studentKR: "이건 평범하게 느껴져요.", keywords: ["no distinctive voice", "predictable form", "visual cliché", "template-like"], professorEN: "Generic means the design follows predictable conventions without a distinctive voice. The forms, colors, and layout feel like they could belong to any project, so the work does not communicate a specific attitude or authorship.", professorKR: "평범하다는 말은 디자인이 뚜렷한 목소리 없이 예측 가능한 관습을 따른다는 뜻입니다. 형태, 색, 레이아웃이 어떤 프로젝트에도 속할 수 있는 것처럼 느껴지기 때문에, 작업은 특정 태도나 작가성을 전달하지 못합니다." },
  { id: 57, studentEN: "The spacing feels inconsistent.", studentKR: "간격이 일관되지 않아요.", keywords: ["spacing system", "visual rhythm", "margin consistency", "grid discipline"], professorEN: "Inconsistent spacing breaks the visual rhythm and makes the composition feel uncontrolled. A spacing system, even a simple one, gives the viewer a sense of underlying order and makes the design feel more disciplined.", professorKR: "일관되지 않은 간격은 시각 리듬을 깨고 구성을 통제되지 않은 것처럼 느끼게 합니다. 간단한 것이라도 간격 시스템은 관람자에게 내재된 질서감을 주고 디자인을 더 규율 있게 느끼게 합니다." },
  { id: 58, studentEN: "This one feels too centered.", studentKR: "이건 너무 가운데 정렬된 것 같아요.", keywords: ["symmetry", "static composition", "off-center tension", "asymmetric energy"], professorEN: "Centered composition can feel stable but also static. If the design needs more energy, an off-center placement or asymmetric tension can create visual movement without losing the sense of balance.", professorKR: "가운데 정렬된 구성은 안정적이지만 정적으로 느껴질 수 있습니다. 디자인에 더 많은 에너지가 필요하다면, 중심에서 벗어난 배치나 비대칭적 긴장이 균형감을 잃지 않고도 시각적 움직임을 만들 수 있습니다." },
  { id: 59, studentEN: "This one feels more alive.", studentKR: "이게 더 살아있는 느낌이에요.", keywords: ["visual energy", "active composition", "tension", "movement", "contrast"], professorEN: "That aliveness comes from visual energy created by tension, movement, and contrast. The composition does not feel settled; it feels like it is in the middle of a visual event, which keeps the viewer engaged.", professorKR: "그 생동감은 긴장, 움직임, 대비가 만들어내는 시각적 에너지에서 나옵니다. 구성이 안정된 것처럼 느껴지지 않고, 시각적 사건의 한가운데에 있는 것처럼 느껴져 관람자의 참여를 유지합니다." },
  { id: 60, studentEN: "This one feels more resolved than before.", studentKR: "이전보다 더 완성된 것 같아요.", keywords: ["design iteration", "visual improvement", "resolved system", "purposeful revision"], professorEN: "You are noticing the improvement from iteration. The revision has resolved some of the earlier tensions, and the visual system now feels more coherent. Each design decision is now supporting the others rather than working against them.", professorKR: "당신은 반복 작업으로 인한 개선을 보고 있습니다. 수정이 이전의 긴장 일부를 해결했고, 시각 시스템이 이제 더 일관되게 느껴집니다. 각 디자인 결정이 이제 서로를 지지하고 있습니다." },
  { id: 61, studentEN: "The hierarchy feels clearer now.", studentKR: "위계가 이제 더 명확해졌어요.", keywords: ["visual hierarchy", "reading sequence", "scale contrast", "weight differentiation"], professorEN: "The clearer hierarchy means the viewer can now read the information in the intended sequence. The scale contrast and weight differentiation are working together to guide the eye from the most important element to the supporting details.", professorKR: "더 명확한 위계는 관람자가 이제 의도된 순서로 정보를 읽을 수 있다는 뜻입니다. 스케일 대비와 무게 차별화가 함께 작동하여 시선을 가장 중요한 요소에서 지지하는 세부 사항으로 안내합니다." },
  { id: 62, studentEN: "The composition feels tighter now.", studentKR: "구성이 이제 더 탄탄해졌어요.", keywords: ["compositional tightness", "visual cohesion", "no wasted space", "purposeful placement"], professorEN: "A tighter composition means every element is placed with purpose and nothing feels wasted. The relationship between the parts is now stronger, and the visual system holds together as a coherent whole.", professorKR: "더 탄탄한 구성은 모든 요소가 목적을 가지고 배치되어 낭비되는 것이 없다는 뜻입니다. 부분들 사이의 관계가 이제 더 강해졌고, 시각 시스템이 일관된 전체로 유지됩니다." },
  { id: 63, studentEN: "The concept feels stronger now.", studentKR: "개념이 이제 더 강해졌어요.", keywords: ["concept clarity", "form-concept alignment", "visual argument", "design intention"], professorEN: "A stronger concept means the visual form is now more fully aligned with the idea. The design is not just solving a layout problem; it is making a visual argument, and the viewer can sense the intention behind every decision.", professorKR: "더 강한 개념은 시각 형식이 이제 아이디어와 더 완전히 정렬되었다는 뜻입니다. 디자인은 단순히 레이아웃 문제를 해결하는 것이 아니라 시각적 주장을 하고 있으며, 관람자는 모든 결정 뒤의 의도를 감지할 수 있습니다." },
  { id: 64, studentEN: "The color feels more unified now.", studentKR: "색이 이제 더 통일된 것 같아요.", keywords: ["color system", "palette coherence", "value consistency", "chromatic unity"], professorEN: "A unified color system means the palette is working as a whole rather than as separate choices. The value relationships and saturation levels are consistent, so the colors support each other and reinforce the overall visual tone.", professorKR: "통일된 색 시스템은 팔레트가 별개의 선택이 아니라 전체로 작동한다는 뜻입니다. 명도 관계와 채도 수준이 일관되어, 색들이 서로를 지지하고 전체적인 시각 톤을 강화합니다." },
  { id: 65, studentEN: "The typography feels more controlled now.", studentKR: "타이포그래피가 이제 더 통제된 것 같아요.", keywords: ["typographic control", "consistent type system", "scale hierarchy", "weight contrast"], professorEN: "Controlled typography means the type system is now consistent in its scale hierarchy, weight contrast, and spacing. The viewer can trust the typographic decisions, and the text supports the visual structure rather than competing with it.", professorKR: "통제된 타이포그래피는 서체 시스템이 이제 스케일 위계, 무게 대비, 간격에서 일관되다는 뜻입니다. 관람자는 타이포그래픽 결정을 신뢰할 수 있고, 텍스트는 시각 구조와 경쟁하지 않고 그것을 지지합니다." },
  { id: 66, studentEN: "The negative space feels more intentional now.", studentKR: "네거티브 스페이스가 이제 더 의도적으로 느껴져요.", keywords: ["intentional negative space", "breathing room", "visual silence", "figure-ground clarity"], professorEN: "Intentional negative space means the empty areas are now supporting the composition rather than just filling unused zones. The breathing room allows the main elements to stand out more clearly and gives the viewer space to rest.", professorKR: "의도적인 네거티브 스페이스는 빈 영역이 이제 단순히 사용되지 않은 구역을 채우는 것이 아니라 구성을 지지한다는 뜻입니다. 숨 쉴 공간은 주요 요소들이 더 명확하게 돋보이게 하고 관람자에게 쉴 공간을 줍니다." },
  { id: 67, studentEN: "The grid feels more visible now.", studentKR: "그리드가 이제 더 느껴져요.", keywords: ["grid structure", "underlying order", "alignment consistency", "visual discipline"], professorEN: "A visible grid does not mean the grid lines are literally showing; it means the viewer can sense the underlying order through consistent alignment and spacing. The grid is the invisible skeleton that holds the composition together.", professorKR: "그리드가 보인다는 말은 그리드 선이 문자 그대로 보인다는 뜻이 아닙니다. 관람자가 일관된 정렬과 간격을 통해 내재된 질서를 감지할 수 있다는 뜻입니다. 그리드는 구성을 하나로 유지하는 보이지 않는 골격입니다." },
  { id: 68, studentEN: "The image feels more powerful now.", studentKR: "이미지가 이제 더 강력하게 느껴져요.", keywords: ["image impact", "cropping", "scale", "figure-ground", "visual force"], professorEN: "A more powerful image usually comes from a stronger crop, a larger scale, or a clearer figure-ground relationship. The image is now doing more visual work, and the viewer responds to it with more intensity.", professorKR: "더 강력한 이미지는 보통 더 강한 크롭, 더 큰 스케일, 또는 더 명확한 전경-배경 관계에서 나옵니다. 이미지가 이제 더 많은 시각적 작업을 하고 있으며, 관람자는 더 강하게 반응합니다." },
  { id: 69, studentEN: "The layout feels more dynamic now.", studentKR: "레이아웃이 이제 더 역동적으로 느껴져요.", keywords: ["dynamic layout", "diagonal tension", "scale variation", "visual movement"], professorEN: "A more dynamic layout means the composition now has more visual movement. The scale variation, diagonal tension, or asymmetric placement is creating energy that pulls the viewer through the design.", professorKR: "더 역동적인 레이아웃은 구성이 이제 더 많은 시각적 움직임을 가진다는 뜻입니다. 스케일 변화, 대각선 긴장, 또는 비대칭적 배치가 관람자를 디자인을 통해 끌어당기는 에너지를 만들고 있습니다." },
  { id: 70, studentEN: "The overall design feels more coherent now.", studentKR: "전체 디자인이 이제 더 일관되게 느껴져요.", keywords: ["design coherence", "visual system unity", "consistent language", "Gestalt"], professorEN: "Coherence means the whole design is now speaking one visual language. The color, type, spacing, and form decisions are all part of the same system, so the viewer reads the work as a unified Gestalt rather than a collection of separate parts.", professorKR: "일관성은 전체 디자인이 이제 하나의 시각 언어를 말한다는 뜻입니다. 색, 서체, 간격, 형태 결정이 모두 같은 시스템의 일부이기 때문에, 관람자는 작업을 별개 부분들의 모음이 아니라 통합된 게슈탈트로 읽습니다." },
  { id: 71, studentEN: "I want to make this feel more energetic.", studentKR: "이걸 더 에너지 있게 만들고 싶어요.", keywords: ["visual energy", "contrast increase", "diagonal movement", "rhythm acceleration"], professorEN: "To increase energy, consider increasing contrast, introducing diagonal movement, or accelerating the visual rhythm. You can also try a scale shift that creates a sudden change in visual velocity.", professorKR: "에너지를 높이려면 대비를 높이거나, 대각선 움직임을 도입하거나, 시각 리듬을 가속하는 것을 고려해보세요. 시각적 속도감에 갑작스러운 변화를 만드는 스케일 변화도 시도해볼 수 있습니다." },
  { id: 72, studentEN: "I want to make this feel calmer.", studentKR: "이걸 더 차분하게 만들고 싶어요.", keywords: ["visual calm", "contrast reduction", "horizontal structure", "slow rhythm"], professorEN: "To create calm, reduce contrast, use horizontal structures, and slow the visual rhythm. Generous negative space and a restrained palette will lower the visual temperature and invite a more contemplative viewing experience.", professorKR: "차분함을 만들려면 대비를 줄이고, 수평 구조를 사용하고, 시각 리듬을 늦추세요. 넉넉한 네거티브 스페이스와 절제된 팔레트는 시각적 온도를 낮추고 더 사색적인 관람 경험을 초대합니다." },
  { id: 73, studentEN: "I want to make the hierarchy clearer.", studentKR: "위계를 더 명확하게 만들고 싶어요.", keywords: ["hierarchy clarification", "scale contrast", "weight differentiation", "reading sequence"], professorEN: "To clarify hierarchy, increase the scale contrast between the primary and secondary elements, and use weight differentiation in the typography. The viewer should be able to read the composition in a clear sequence without having to search.", professorKR: "위계를 명확히 하려면 1차 요소와 2차 요소 사이의 스케일 대비를 높이고, 타이포그래피에서 무게 차별화를 사용하세요. 관람자는 찾지 않고도 명확한 순서로 구성을 읽을 수 있어야 합니다." },
  { id: 74, studentEN: "I want to make this feel more minimal.", studentKR: "이걸 더 미니멀하게 만들고 싶어요.", keywords: ["reduction", "essential elements", "negative space expansion", "visual editing"], professorEN: "To move toward minimal, start by removing elements that are not essential to the message. Ask yourself: if this element were removed, would the communication still work? If yes, remove it. Minimal design is about visual editing, not just simplicity.", professorKR: "미니멀로 나아가려면 메시지에 필수적이지 않은 요소를 제거하는 것부터 시작하세요. 스스로에게 물어보세요: 이 요소를 제거해도 커뮤니케이션이 여전히 작동하는가? 그렇다면 제거하세요. 미니멀 디자인은 단순함이 아니라 시각적 편집에 관한 것입니다." },
  { id: 75, studentEN: "I want to add more visual tension.", studentKR: "시각적 긴장감을 더 추가하고 싶어요.", keywords: ["visual tension", "contrast", "scale opposition", "directional conflict"], professorEN: "To add tension, introduce contrast between opposing forces: large versus small, dark versus light, static versus dynamic. You can also create directional conflict by placing elements that pull the viewer's eye in different directions simultaneously.", professorKR: "긴장을 추가하려면 대립하는 힘 사이의 대비를 도입하세요: 크고 작음, 어둡고 밝음, 정적이고 역동적임. 관람자의 시선을 동시에 다른 방향으로 끌어당기는 요소를 배치하여 방향 충돌을 만들 수도 있습니다." },
  { id: 76, studentEN: "I want to improve the color palette.", studentKR: "색 팔레트를 개선하고 싶어요.", keywords: ["color palette development", "value structure", "chromatic temperature", "palette coherence"], professorEN: "To improve the palette, first establish a clear value structure: decide which colors will be light, mid, and dark. Then consider the chromatic temperature: are the colors warm, cool, or neutral? A coherent palette usually has a dominant temperature with one or two accents.", professorKR: "팔레트를 개선하려면 먼저 명확한 명도 구조를 확립하세요: 어떤 색이 밝고, 중간이고, 어두울지 결정하세요. 그런 다음 색채 온도를 고려하세요: 색들이 따뜻한가요, 차가운가요, 중성인가요? 일관된 팔레트는 보통 하나 또는 두 개의 액센트와 함께 지배적인 온도를 가집니다." },
  { id: 77, studentEN: "I want to make the type feel more expressive.", studentKR: "서체를 더 표현적으로 만들고 싶어요.", keywords: ["expressive typography", "scale variation", "weight play", "typographic gesture"], professorEN: "Expressive typography uses scale variation, weight contrast, and placement as visual gestures. The type can lean, break the grid, or change scale dramatically to become part of the image rather than just a label.", professorKR: "표현적인 타이포그래피는 스케일 변화, 무게 대비, 배치를 시각적 제스처로 사용합니다. 서체는 기울거나, 그리드를 깨거나, 스케일을 극적으로 변화시켜 단순한 레이블이 아니라 이미지의 일부가 될 수 있습니다." },
  { id: 78, studentEN: "I want to make the composition feel more grounded.", studentKR: "구성을 더 안정감 있게 만들고 싶어요.", keywords: ["compositional grounding", "visual anchor", "baseline stability", "weight distribution"], professorEN: "To ground the composition, introduce a strong visual anchor, such as a heavy baseline element or a dominant horizontal plane. Distributing visual weight toward the lower portion of the composition also creates a sense of stability.", professorKR: "구성을 안정시키려면 무거운 기준선 요소나 지배적인 수평 면 같은 강한 시각적 앵커를 도입하세요. 구성의 하단 부분으로 시각적 무게를 분배하는 것도 안정감을 만듭니다." },
  { id: 79, studentEN: "I want to make the image feel more integrated.", studentKR: "이미지를 더 통합적으로 만들고 싶어요.", keywords: ["image integration", "type-image relationship", "shared color", "visual continuity"], professorEN: "To integrate the image more fully, try sharing a color from the image in the typography or background, or let the type overlap with the image in a way that creates a visual conversation. The image and text should feel like they belong to the same visual world.", professorKR: "이미지를 더 완전히 통합하려면 이미지의 색을 타이포그래피나 배경에서 공유하거나, 서체가 이미지와 겹쳐 시각적 대화를 만드는 방식으로 배치해보세요. 이미지와 텍스트는 같은 시각 세계에 속하는 것처럼 느껴져야 합니다." },
  { id: 80, studentEN: "I want to make the concept more visible.", studentKR: "개념을 더 가시적으로 만들고 싶어요.", keywords: ["concept visualization", "form as idea", "visual metaphor", "concept-form unity"], professorEN: "To make the concept more visible, ask how the form itself can embody the idea. The layout, color, and typography should not just describe the concept but perform it. The design should make the viewer feel the idea, not just read it.", professorKR: "개념을 더 가시적으로 만들려면 형식 자체가 어떻게 아이디어를 구현할 수 있는지 물어보세요. 레이아웃, 색, 타이포그래피는 단순히 개념을 설명하는 것이 아니라 그것을 수행해야 합니다. 디자인은 관람자가 아이디어를 읽는 것이 아니라 느끼게 해야 합니다." },
  { id: 81, studentEN: "Let me ask you about your concept.", studentKR: "개념에 대해 물어볼게요.", keywords: ["concept inquiry", "design intention", "visual argument", "communication goal"], professorEN: "Let me ask you about your concept. What is the central visual argument you are trying to make? Every design decision should serve that argument, so it is important to be able to state it clearly before we evaluate the form.", professorKR: "개념에 대해 물어볼게요. 당신이 만들려는 핵심 시각적 주장은 무엇인가요? 모든 디자인 결정이 그 주장을 위해 작동해야 하기 때문에, 형식을 평가하기 전에 그것을 명확하게 말할 수 있는 것이 중요합니다." },
  { id: 82, studentEN: "What was your intention with this choice?", studentKR: "이 선택의 의도가 무엇이었나요?", keywords: ["design intention", "purposeful decision", "visual reasoning", "concept alignment"], professorEN: "Good question to ask yourself. What was your intention with this choice? Every visual decision should have a reason that connects back to the concept. If you cannot articulate the reason, the choice may need to be reconsidered.", professorKR: "스스로에게 좋은 질문입니다. 이 선택의 의도가 무엇이었나요? 모든 시각적 결정은 개념으로 연결되는 이유를 가져야 합니다. 이유를 말할 수 없다면, 그 선택은 재고될 필요가 있을 수 있습니다." },
  { id: 83, studentEN: "How does this relate to your concept?", studentKR: "이게 당신의 개념과 어떻게 연결되나요?", keywords: ["concept-form relationship", "visual logic", "design coherence", "intentional connection"], professorEN: "Let's trace the connection. How does this visual decision relate to your concept? The strongest designs have a clear logic that connects every formal choice back to the central idea, so the viewer experiences the concept through the form.", professorKR: "연결을 추적해봅시다. 이 시각적 결정이 당신의 개념과 어떻게 연결되나요? 가장 강한 디자인은 모든 형식적 선택을 핵심 아이디어로 연결하는 명확한 논리를 가지고 있어, 관람자가 형식을 통해 개념을 경험합니다." },
  { id: 84, studentEN: "What is the viewer supposed to feel?", studentKR: "관람자가 어떤 감정을 느끼길 원하나요?", keywords: ["viewer experience", "emotional intention", "visual communication", "design empathy"], professorEN: "What is the viewer supposed to feel? Design is a form of communication, and the emotional response of the viewer is part of the message. If you can define the intended feeling clearly, you can evaluate whether the visual decisions are supporting or contradicting it.", professorKR: "관람자가 어떤 감정을 느끼길 원하나요? 디자인은 커뮤니케이션의 한 형태이며, 관람자의 감정적 반응은 메시지의 일부입니다. 의도된 감정을 명확하게 정의할 수 있다면, 시각적 결정이 그것을 지지하는지 모순하는지 평가할 수 있습니다." },
  { id: 85, studentEN: "Who is the audience for this design?", studentKR: "이 디자인의 대상 관람자는 누구인가요?", keywords: ["audience awareness", "communication context", "design purpose", "visual register"], professorEN: "Audience awareness is fundamental to design. The visual register, complexity, and tone of the design should be calibrated to the audience's expectations and context. A design that works for one audience may feel wrong for another.", professorKR: "관람자 인식은 디자인의 기본입니다. 디자인의 시각적 레지스터, 복잡성, 톤은 관람자의 기대와 맥락에 맞게 조정되어야 합니다. 한 관람자에게 효과적인 디자인이 다른 관람자에게는 잘못된 것처럼 느껴질 수 있습니다." },
  { id: 86, studentEN: "What is the most important element here?", studentKR: "여기서 가장 중요한 요소는 무엇인가요?", keywords: ["priority decision", "dominant element", "visual hierarchy", "design focus"], professorEN: "Identifying the most important element is the first step in building a clear hierarchy. Once you know what the viewer must see first, you can organize all other elements in relation to that priority.", professorKR: "가장 중요한 요소를 파악하는 것이 명확한 위계를 구축하는 첫 번째 단계입니다. 관람자가 먼저 무엇을 봐야 하는지 알면, 그 우선순위와 관련하여 다른 모든 요소를 조직할 수 있습니다." },
  { id: 87, studentEN: "What would you remove from this design?", studentKR: "이 디자인에서 무엇을 제거하겠어요?", keywords: ["visual editing", "reduction", "essential elements", "design discipline"], professorEN: "The ability to remove is as important as the ability to add. Ask yourself: what is the minimum number of elements needed to communicate the idea? Everything beyond that minimum is a candidate for removal.", professorKR: "제거하는 능력은 추가하는 능력만큼 중요합니다. 스스로에게 물어보세요: 아이디어를 전달하는 데 필요한 최소한의 요소는 몇 개인가요? 그 최소한을 넘는 모든 것은 제거 후보입니다." },
  { id: 88, studentEN: "What would you keep from this design?", studentKR: "이 디자인에서 무엇을 유지하겠어요?", keywords: ["design strengths", "visual assets", "core decisions", "building on success"], professorEN: "Identifying what to keep is as important as identifying what to change. The strongest elements are the foundation for the next iteration. Build on what is working rather than starting from scratch.", professorKR: "무엇을 유지할지 파악하는 것은 무엇을 바꿀지 파악하는 것만큼 중요합니다. 가장 강한 요소들이 다음 반복 작업의 기초입니다. 처음부터 다시 시작하기보다 작동하는 것을 기반으로 구축하세요." },
  { id: 89, studentEN: "How would you describe the visual language of this work?", studentKR: "이 작업의 시각 언어를 어떻게 설명하겠어요?", keywords: ["visual language", "formal vocabulary", "design system", "visual identity"], professorEN: "Visual language is the consistent system of forms, colors, and spatial relationships that gives a design its identity. Describing the visual language means identifying the recurring decisions that make this work recognizable as a coherent system.", professorKR: "시각 언어는 디자인에 정체성을 부여하는 형태, 색, 공간 관계의 일관된 시스템입니다. 시각 언어를 설명하는 것은 이 작업을 일관된 시스템으로 인식하게 만드는 반복적인 결정들을 파악하는 것을 의미합니다." },
  { id: 90, studentEN: "What is the strongest aspect of this design?", studentKR: "이 디자인의 가장 강한 부분은 무엇인가요?", keywords: ["design strengths", "critical evaluation", "visual success", "positive critique"], professorEN: "Identifying the strongest aspect requires the same critical eye as identifying weaknesses. The strongest aspect is usually the decision that most clearly expresses the concept or creates the most powerful visual experience.", professorKR: "가장 강한 부분을 파악하는 것은 약점을 파악하는 것과 같은 비판적 시각을 필요로 합니다. 가장 강한 부분은 보통 개념을 가장 명확하게 표현하거나 가장 강력한 시각 경험을 만드는 결정입니다." },
  { id: 91, studentEN: "What needs the most improvement?", studentKR: "가장 개선이 필요한 부분은 무엇인가요?", keywords: ["design weakness", "critical evaluation", "improvement priority", "visual problem"], professorEN: "Prioritizing improvement means identifying the visual problem that is most damaging to the communication. Start with the issue that most prevents the viewer from understanding the concept, and address that before moving to secondary concerns.", professorKR: "개선의 우선순위를 정하는 것은 커뮤니케이션에 가장 해로운 시각적 문제를 파악하는 것을 의미합니다. 관람자가 개념을 이해하는 것을 가장 방해하는 문제부터 시작하고, 그것을 해결한 후 부차적인 문제로 넘어가세요." },
  { id: 92, studentEN: "How does this compare to your previous version?", studentKR: "이전 버전과 비교해서 어떤가요?", keywords: ["design iteration", "comparative evaluation", "improvement tracking", "design development"], professorEN: "Comparative evaluation is a key skill in design. When comparing versions, focus on whether the changes have resolved the previous problems without creating new ones. Iteration should move the design closer to the concept, not just make it different.", professorKR: "비교 평가는 디자인의 핵심 기술입니다. 버전을 비교할 때, 변경 사항이 새로운 문제를 만들지 않고 이전 문제를 해결했는지에 집중하세요. 반복 작업은 디자인을 단순히 다르게 만드는 것이 아니라 개념에 더 가깝게 이동시켜야 합니다." },
  { id: 93, studentEN: "What visual references did you use?", studentKR: "어떤 시각적 레퍼런스를 사용했나요?", keywords: ["visual references", "design research", "influence awareness", "critical distance"], professorEN: "Knowing your visual references is important for understanding your own design decisions. References can inspire, but they should be transformed into your own visual language rather than directly copied. What did you take from the reference, and what did you change?", professorKR: "시각적 레퍼런스를 아는 것은 자신의 디자인 결정을 이해하는 데 중요합니다. 레퍼런스는 영감을 줄 수 있지만, 직접 복사하기보다 자신의 시각 언어로 변환되어야 합니다. 레퍼런스에서 무엇을 가져왔고, 무엇을 바꿨나요?" },
  { id: 94, studentEN: "How does this work in context?", studentKR: "이게 맥락 안에서 어떻게 작동하나요?", keywords: ["design context", "environmental consideration", "scale and medium", "contextual reading"], professorEN: "Context changes how a design is read. A poster that works at small scale may fail at large scale, and a design that works in print may not translate to screen. Always consider how the medium, scale, and environment will affect the viewer's experience.", professorKR: "맥락은 디자인이 읽히는 방식을 바꿉니다. 작은 스케일에서 효과적인 포스터가 큰 스케일에서는 실패할 수 있고, 인쇄에서 효과적인 디자인이 화면으로 번역되지 않을 수 있습니다. 항상 매체, 스케일, 환경이 관람자의 경험에 어떤 영향을 미칠지 고려하세요." },
  { id: 95, studentEN: "What is the next step for this design?", studentKR: "이 디자인의 다음 단계는 무엇인가요?", keywords: ["design development", "next iteration", "improvement strategy", "design process"], professorEN: "Identifying the next step means knowing which problem to solve first. Prioritize the change that will have the most impact on the communication, and make that change before addressing secondary issues. Design development is a sequence of focused decisions.", professorKR: "다음 단계를 파악하는 것은 어떤 문제를 먼저 해결할지 아는 것을 의미합니다. 커뮤니케이션에 가장 큰 영향을 미칠 변화를 우선시하고, 부차적인 문제를 다루기 전에 그 변화를 만드세요. 디자인 개발은 집중된 결정의 순서입니다." },
  { id: 96, studentEN: "This design communicates clearly.", studentKR: "이 디자인은 명확하게 전달돼요.", keywords: ["clear communication", "aligned concept and form", "effective hierarchy", "message delivery"], professorEN: "Clear communication means the concept and form are aligned, and the viewer can understand the message without effort. The hierarchy guides the eye, the visual language supports the idea, and the composition holds together as a coherent whole.", professorKR: "명확한 커뮤니케이션은 개념과 형식이 정렬되어 있고, 관람자가 노력 없이 메시지를 이해할 수 있다는 뜻입니다. 위계가 시선을 안내하고, 시각 언어가 아이디어를 지지하며, 구성이 일관된 전체로 유지됩니다." },
  { id: 97, studentEN: "This design has a strong visual identity.", studentKR: "이 디자인은 강한 시각 정체성을 가지고 있어요.", keywords: ["visual identity", "consistent system", "recognizable language", "authorial voice"], professorEN: "A strong visual identity means the design has a recognizable language that is consistent across all elements. The color, type, and form decisions work together as a system, giving the work an authorial voice that is distinct and memorable.", professorKR: "강한 시각 정체성은 디자인이 모든 요소에 걸쳐 일관된 인식 가능한 언어를 가진다는 뜻입니다. 색, 서체, 형태 결정이 시스템으로 함께 작동하여, 작업에 뚜렷하고 기억에 남는 작가적 목소리를 부여합니다." },
  { id: 98, studentEN: "This design solves the problem well.", studentKR: "이 디자인은 문제를 잘 해결했어요.", keywords: ["problem solving", "design effectiveness", "communication success", "functional design"], professorEN: "Effective design solves the communication problem clearly and efficiently. The visual decisions are not just aesthetically interesting; they are functionally appropriate, meaning they serve the audience, the context, and the message simultaneously.", professorKR: "효과적인 디자인은 커뮤니케이션 문제를 명확하고 효율적으로 해결합니다. 시각적 결정은 단순히 미적으로 흥미로운 것이 아니라 기능적으로 적절합니다. 즉, 관람자, 맥락, 메시지를 동시에 섬깁니다." },
  { id: 99, studentEN: "This design shows strong design thinking.", studentKR: "이 디자인은 강한 디자인 사고를 보여줘요.", keywords: ["design thinking", "systematic approach", "concept development", "visual reasoning"], professorEN: "Strong design thinking means the work shows evidence of a systematic approach: a clear concept, a developed visual language, and a series of intentional decisions that move from idea to form. The design does not just look good; it thinks well.", professorKR: "강한 디자인 사고는 작업이 체계적인 접근의 증거를 보여준다는 뜻입니다: 명확한 개념, 발전된 시각 언어, 아이디어에서 형식으로 이동하는 일련의 의도적인 결정. 디자인은 단순히 좋아 보이는 것이 아니라 잘 생각합니다." },
  { id: 100, studentEN: "This one communicates well.", studentKR: "이건 메시지가 잘 전달돼요.", keywords: ["message delivery", "aligned concept and form", "reading sequence"], professorEN: "The communication works because the concept and form are aligned, and the viewer can understand the message clearly. The hierarchy, figure-ground relationship, and sequence of reading all support the intended idea instead of distracting from it.", professorKR: "커뮤니케이션이 잘 작동하는 이유는 개념과 형식이 정렬되어 있고, 관람자가 메시지를 분명하게 이해할 수 있기 때문입니다. 위계, 전경-배경 관계, 읽기의 순서가 모두 의도한 아이디어를 방해하지 않고 지지하고 있습니다." },
];

export const STAGES: Stage[] = [
  {
    id: 1,
    title: "Visual Impact & Contrast",
    titleKR: "시각적 임팩트와 대비",
    icon: "⚡",
    colorClass: "lime",
    description: "Learn to articulate visual impact, contrast, and hierarchy in design critique.",
    descriptionKR: "디자인 크리틱에서 시각적 임팩트, 대비, 위계를 표현하는 방법을 학습합니다.",
    sentences: ALL_SENTENCES.slice(0, 10),
  },
  {
    id: 2,
    title: "Balance & Composition",
    titleKR: "균형과 구성",
    icon: "⚖️",
    colorClass: "blue",
    description: "Master the language of compositional balance, visual weight, and spatial organization.",
    descriptionKR: "구성의 균형, 시각적 무게, 공간 조직에 관한 언어를 마스터합니다.",
    sentences: ALL_SENTENCES.slice(10, 20),
  },
  {
    id: 3,
    title: "Rhythm & Movement",
    titleKR: "리듬과 움직임",
    icon: "🌊",
    colorClass: "purple",
    description: "Describe visual rhythm, movement, and dynamic energy in compositions.",
    descriptionKR: "구성에서 시각적 리듬, 움직임, 역동적 에너지를 묘사하는 방법을 학습합니다.",
    sentences: ALL_SENTENCES.slice(20, 30),
  },
  {
    id: 4,
    title: "Mood & Atmosphere",
    titleKR: "분위기와 감성",
    icon: "🎭",
    colorClass: "orange",
    description: "Articulate the emotional and atmospheric qualities of graphic design work.",
    descriptionKR: "그래픽 디자인 작업의 감정적, 분위기적 특성을 표현하는 방법을 학습합니다.",
    sentences: ALL_SENTENCES.slice(30, 40),
  },
  {
    id: 5,
    title: "Space & Depth",
    titleKR: "공간과 깊이",
    icon: "🔭",
    colorClass: "teal",
    description: "Discuss spatial hierarchy, depth, and the figure-ground relationship.",
    descriptionKR: "공간 위계, 깊이, 전경-배경 관계에 대해 논의하는 방법을 학습합니다.",
    sentences: ALL_SENTENCES.slice(40, 50),
  },
  {
    id: 6,
    title: "Typography & Legibility",
    titleKR: "타이포그래피와 가독성",
    icon: "📝",
    colorClass: "red",
    description: "Evaluate typographic decisions, legibility, and text-image relationships.",
    descriptionKR: "타이포그래피 결정, 가독성, 텍스트-이미지 관계를 평가하는 방법을 학습합니다.",
    sentences: ALL_SENTENCES.slice(50, 60),
  },
  {
    id: 7,
    title: "Design Development",
    titleKR: "디자인 발전",
    icon: "🔄",
    colorClass: "indigo",
    description: "Guide iterative design improvement and articulate design development.",
    descriptionKR: "반복적인 디자인 개선을 안내하고 디자인 발전을 표현하는 방법을 학습합니다.",
    sentences: ALL_SENTENCES.slice(60, 70),
  },
  {
    id: 8,
    title: "Design Direction",
    titleKR: "디자인 방향 제시",
    icon: "🧭",
    colorClass: "yellow",
    description: "Provide constructive direction for improving specific design qualities.",
    descriptionKR: "특정 디자인 품질 개선을 위한 건설적인 방향을 제시하는 방법을 학습합니다.",
    sentences: ALL_SENTENCES.slice(70, 80),
  },
  {
    id: 9,
    title: "Critical Dialogue",
    titleKR: "비판적 대화",
    icon: "💬",
    colorClass: "pink",
    description: "Engage in critical dialogue about design concepts and intentions.",
    descriptionKR: "디자인 개념과 의도에 대한 비판적 대화에 참여하는 방법을 학습합니다.",
    sentences: ALL_SENTENCES.slice(80, 90),
  },
  {
    id: 10,
    title: "Advanced Critique",
    titleKR: "심화 크리틱",
    icon: "🏆",
    colorClass: "gold",
    description: "Master comprehensive design evaluation and professional critique language.",
    descriptionKR: "종합적인 디자인 평가와 전문적인 크리틱 언어를 마스터합니다.",
    sentences: ALL_SENTENCES.slice(90, 100),
  },
];

export type QuizType = 'fill-blank' | 'multiple-choice' | 'short-answer' | 'kr-to-en' | 'en-to-kr';

export const QUIZ_TYPES: QuizType[] = ['fill-blank', 'multiple-choice', 'short-answer', 'kr-to-en', 'en-to-kr'];

export function getQuizTypeLabel(type: QuizType): string {
  const labels: Record<QuizType, string> = {
    'fill-blank': '빈칸 채우기',
    'multiple-choice': '객관식',
    'short-answer': '주관식',
    'kr-to-en': '한→영 전환',
    'en-to-kr': '영→한 전환',
  };
  return labels[type];
}

export function getQuizTypeIcon(type: QuizType): string {
  const icons: Record<QuizType, string> = {
    'fill-blank': '✏️',
    'multiple-choice': '🔘',
    'short-answer': '📝',
    'kr-to-en': '🇰🇷→🇺🇸',
    'en-to-kr': '🇺🇸→🇰🇷',
  };
  return icons[type];
}
